#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Com.Loonytone.Droid.PullToRefresh.Resource", IsApplication=false)]

namespace Com.Loonytone.Droid.PullToRefresh
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int slide_in_from_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int slide_in_from_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int slide_out_to_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int slide_out_to_top = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010015
			public static int ptrAdapterViewBackground = 2130771989;
			
			// aapt resource value: 0x7f010010
			public static int ptrAnimationStyle = 2130771984;
			
			// aapt resource value: 0x7f01000a
			public static int ptrDrawable = 2130771978;
			
			// aapt resource value: 0x7f010017
			public static int ptrDrawableBottom = 2130771991;
			
			// aapt resource value: 0x7f01000c
			public static int ptrDrawableEnd = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public static int ptrDrawableStart = 2130771979;
			
			// aapt resource value: 0x7f010016
			public static int ptrDrawableTop = 2130771990;
			
			// aapt resource value: 0x7f010005
			public static int ptrHeaderBackground = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int ptrHeaderSubTextColor = 2130771975;
			
			// aapt resource value: 0x7f01000e
			public static int ptrHeaderTextAppearance = 2130771982;
			
			// aapt resource value: 0x7f010006
			public static int ptrHeaderTextColor = 2130771974;
			
			// aapt resource value: 0x7f010012
			public static int ptrListViewExtrasEnabled = 2130771986;
			
			// aapt resource value: 0x7f010008
			public static int ptrMode = 2130771976;
			
			// aapt resource value: 0x7f01000d
			public static int ptrOverScroll = 2130771981;
			
			// aapt resource value: 0x7f010013
			public static int ptrRecyclerViewExtrasEnabled = 2130771987;
			
			// aapt resource value: 0x7f010004
			public static int ptrRefreshableViewBackground = 2130771972;
			
			// aapt resource value: 0x7f010014
			public static int ptrRotateDrawableWhilePulling = 2130771988;
			
			// aapt resource value: 0x7f010011
			public static int ptrScrollingWhileRefreshingEnabled = 2130771985;
			
			// aapt resource value: 0x7f010009
			public static int ptrShowIndicator = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public static int ptrSubHeaderTextAppearance = 2130771983;
			
			// aapt resource value: 0x7f010002
			public static int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050006
			public static int header_footer_left_right_padding = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int header_footer_top_bottom_padding = 2131034119;
			
			// aapt resource value: 0x7f050004
			public static int indicator_corner_radius = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int indicator_internal_padding = 2131034117;
			
			// aapt resource value: 0x7f050003
			public static int indicator_right_padding = 2131034115;
			
			// aapt resource value: 0x7f050000
			public static int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int item_touch_helper_swipe_escape_max_velocity = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int item_touch_helper_swipe_escape_velocity = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int default_ptr_flip = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int default_ptr_rotate = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int indicator_arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int indicator_bg_bottom = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int indicator_bg_top = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public static int both = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int disabled = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public static int fl_inner = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public static int flip = 2131099659;
			
			// aapt resource value: 0x7f060001
			public static int gridview = 2131099649;
			
			// aapt resource value: 0x7f060000
			public static int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060006
			public static int manualOnly = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int pullDownFromTop = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int pullFromEnd = 2131099656;
			
			// aapt resource value: 0x7f060009
			public static int pullFromStart = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public static int pullUpFromBottom = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public static int pull_to_refresh_image = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public static int pull_to_refresh_progress = 2131099663;
			
			// aapt resource value: 0x7f060011
			public static int pull_to_refresh_sub_text = 2131099665;
			
			// aapt resource value: 0x7f060010
			public static int pull_to_refresh_text = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public static int rotate = 2131099660;
			
			// aapt resource value: 0x7f060003
			public static int scrollview = 2131099651;
			
			// aapt resource value: 0x7f060002
			public static int webview = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int pull_to_refresh_header_horizontal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int pull_to_refresh_header_vertical = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public static int pull_to_refresh_pull_label = 2131165184;
			
			// aapt resource value: 0x7f070002
			public static int pull_to_refresh_refreshing_label = 2131165186;
			
			// aapt resource value: 0x7f070001
			public static int pull_to_refresh_release_label = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresh = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 17
			public static int PullToRefresh_ptrAdapterViewBackground = 17;
			
			// aapt resource value: 12
			public static int PullToRefresh_ptrAnimationStyle = 12;
			
			// aapt resource value: 6
			public static int PullToRefresh_ptrDrawable = 6;
			
			// aapt resource value: 19
			public static int PullToRefresh_ptrDrawableBottom = 19;
			
			// aapt resource value: 8
			public static int PullToRefresh_ptrDrawableEnd = 8;
			
			// aapt resource value: 7
			public static int PullToRefresh_ptrDrawableStart = 7;
			
			// aapt resource value: 18
			public static int PullToRefresh_ptrDrawableTop = 18;
			
			// aapt resource value: 1
			public static int PullToRefresh_ptrHeaderBackground = 1;
			
			// aapt resource value: 3
			public static int PullToRefresh_ptrHeaderSubTextColor = 3;
			
			// aapt resource value: 10
			public static int PullToRefresh_ptrHeaderTextAppearance = 10;
			
			// aapt resource value: 2
			public static int PullToRefresh_ptrHeaderTextColor = 2;
			
			// aapt resource value: 14
			public static int PullToRefresh_ptrListViewExtrasEnabled = 14;
			
			// aapt resource value: 4
			public static int PullToRefresh_ptrMode = 4;
			
			// aapt resource value: 9
			public static int PullToRefresh_ptrOverScroll = 9;
			
			// aapt resource value: 15
			public static int PullToRefresh_ptrRecyclerViewExtrasEnabled = 15;
			
			// aapt resource value: 0
			public static int PullToRefresh_ptrRefreshableViewBackground = 0;
			
			// aapt resource value: 16
			public static int PullToRefresh_ptrRotateDrawableWhilePulling = 16;
			
			// aapt resource value: 13
			public static int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 13;
			
			// aapt resource value: 5
			public static int PullToRefresh_ptrShowIndicator = 5;
			
			// aapt resource value: 11
			public static int PullToRefresh_ptrSubHeaderTextAppearance = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public static int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public static int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public static int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public static int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public static int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
